[default]
DEBUG = true
HOST = '0.0.0.0'
PORT = '8000'

[development]
DEBUG = true
POSTGRES_DB_NAME = 
POSTGRES_USER = 
POSTGRES_PASSWORD = 
POSTGRES_HOST = 
POSTGRES_PORT = 

[staging]
DEBUG = true
POSTGRES_DB_NAME = 
POSTGRES_USER = 
POSTGRES_PASSWORD = 
POSTGRES_HOST = 
POSTGRES_PORT = 

[production]
DEBUG = false
POSTGRES_DB_NAME = 
POSTGRES_USER = 
POSTGRES_PASSWORD = 
POSTGRES_HOST = 
POSTGRES_PORT = 